version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: 'go run /app/backend/main.go -b 0.0.0.0:3000'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres_db

  postgres_db:
    container_name: ${DATABASE_HOST}
    image: postgres:15.4
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - .pgdata:/var/lib/postgresql/data
    env_file:
      - .env